productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
]

productos/urls.py
from django.urls import path
#Indica a python que se importe el archivo views de nuestra carpeta
#esto en caso de que alguna dependencia tenga el mismo nombre (Muy comun en este caso)
from . import views

#app_name es el nombre de la aplicacion
#Esto es una convencion de django, si encuentra esta variable agregara el nombre de la aplicacion
#al principio de la url, lo que evita conflictos entre urls de diferentes aplicaciones
app_name='productos'

urlpatterns=[
    path('',views.index,name='index'),
    path('<int:id>',views.detail,name='detalle'),
    path('formulario',views.formulario,name='formulario'),
]

productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categoria(models.Model):
    nombre=models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre=models.CharField(max_length=255)
    stock=models.IntegerField()
    puntaje=models.FloatField()
    #onDelete
    #1.- CASCADE: Borra todos los productos de la categoria
    #2.- PROTECT: No se puede borrar la categoria
    #3.- RESTRICT: No se puede borrar la categoria si tiene productos
    #4.- SET_NULL: Pone en null categoriaId si se borra la categoria
    #5.- SET_DEFAULT: Pone un valor por defecto en categoriaId si se borra la categoria
    
    categoria=models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE
        )
    creado_en=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre    

productos/forms.py
#Para usar formularios en django se debe instalar el paquete django-forms (Productly/settings.py)
#Para crear un formulario se debe importar ModelForm
from django.forms import ModelForm
from .models import Producto

class ProductoForm(ModelForm):
    class Meta:
        #El modelo que debe usar la clase
        model=Producto
        #Los campos que se deben mostrar en el formulario
        fields=['nombre','stock','puntaje','categoria']

productly/views.py
from urllib import request
from django.shortcuts import render


def inicio(request):
    return render(request, 'inicio.html')

productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect,JsonResponse
from django.shortcuts import get_object_or_404, render

from .forms import ProductoForm
from .models import Producto

# Create your views here.

##filter items with stock >= <value>
#Productos=Producto.objects.filter(stock__gte=5)
##filter items with stock <= <value>
#Productos=Producto.objects.filter(stock__lte=5)
def index(request):
    ##Get all items
    productos=Producto.objects.all()
    print(productos)
    return render(request,'index.html',{'productos':productos}) 

    #Por defecto solo serializa diccionarios, por eso usamos safe=False
    #Es neceario convertir el queryset a una lista
    #return JsonResponse(list(productos),safe=False)


##filter by Id
#Productos=Producto.objects.get(id=1)
##Filter by primary-key
#Productos=Producto.objects.get(pk=1)
def detail(request,id):
    
    productoDb=get_object_or_404(Producto,id=id)

    return render(
        request,
        'detalle.html',
        {'producto':productoDb})

def formulario(request):
    if(request.method=='POST'):
        #Validar formulario
        form=ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    #En cas la petición NO es POST, se crea un formulario en blanco
    else:
        form=ProductoForm()
    return render(
        request,
        'producto_form.html',
        {'form':form})

productos/templates/detalle.html
{%extends 'base.html'%} {%block content%}
<h4>{{producto.nombre}}</h4>

<div>
  <p><strong>Stock: </strong>{{producto.stock}}</p>
  <p><strong>Score: </strong>{{producto.puntaje}}</p>
  <p><strong>Category: </strong>{{producto.categoria}}</p>
  <a class="btn btn-sm btn-secondary" href="{%url 'productos:index'%}">Index</a>
</div>
{%endblock%}

productos/templates/index.html
{% extends 'base.html' %} {% block content %}
<h1>Productos</h1>
<a class="btn btn-sm btn-primary" href="{% url "productos:formulario" %}">Add Item</a>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Stock</th>
      <th>Puntaje</th>
      <th>Categoría</th>
    </tr>
  </thead>
  <tbody>
    {% for producto in productos %}
    <tr>
      <td>
        <a href="{%url 'productos:detalle' producto.id%}"
          >{{ producto.nombre }}</a
        >
      </td>
      <td>{{ producto.stock }}</td>
      <td>{{ producto.puntaje }}</td>
      <td>{{ producto.categoria }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

productos/templates/producto_form.html
{%extends 'base.html'%} {% block content %}
<form novalidate action="{% url 'productos:formulario'%}" method="post">
  {% csrf_token %} {{form}}
  <input class="btn btn-sm btn-success" type="submit" value="Enviar" />
</form>

{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Productly</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "inicio" %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "productos:index" %}">Products</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class='form-label' >{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/input.html
<input class="form-control {{ widget.attrs.class }}" type="{{ widget.type }}"
name="{{ widget.name }}" {% if widget.value != None %}
value="{{widget.value|stringformat:'s' }}" {% endif %} {% include
"django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select
    class="form-select" 
    name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>

templates/form_snippet.html
{% load add_attr %} {% for field in form %}
<div class="mb-3">
  {{ field.label_tag }} {% if field.errors %}
  {{field|add_attr:"class:is-invalid"}} {% else %} {{ field }} {% endif %}
  <div class="invalid-feedback">
    {% for error in field.errors %} {{ error }} {% endfor %}
  </div>
</div>
{% endfor %}

templates/inicio.html
{% extends "base.html" %} {% block content %} Hello world! welcome to productly!
{%endblock%}